In [30]:
import numpy as np
import gym
import time
import matplotlib.pyplot as plt

In [6]:
env = gym.make("FrozenLake-v0")
action_size = env.action_space.n
state_size = env.observation_space.n

In [7]:
qtable = np.zeros((state_size, action_size))

In [42]:
total_episodes = 200000
learning_rate = 0.8
max_steps = 99
gamma = 0.95

epsilon = 1.0
max_epsilon = 1.0
min_epsilon = 0.01
decay_rate = 0.005

In [43]:
rewards = []
start = time.time()
for episode in range(total_episodes):
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    for step in range(max_steps):
        exp_exp_tradeoff = np.random.rand()
        
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state,:])            
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
        total_rewards += reward
        
        state = new_state
        
        if done == True:
            break
            
    epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate * episode)
    rewards.append(total_rewards)
print(time.time()-start)

199.17778778076172


In [39]:
print ("Score over time: " +  str(sum(rewards)/total_episodes))
print(qtable)

Score over time: 0.49756
[[1.41182176e-02 1.33360922e-02 1.99982965e-02 1.36154514e-02]
 [4.02487769e-03 2.63625741e-03 4.36726149e-03 7.15019718e-03]
 [2.09517678e-03 1.82991792e-02 5.96793827e-03 6.36081752e-03]
 [3.08836991e-03 1.50890990e-03 2.91829651e-03 6.40657179e-03]
 [2.86399172e-01 1.39075615e-02 2.46889499e-03 7.48849279e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.81462683e-03 4.96077873e-05 1.01154551e-04 1.91642318e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.41769126e-02 1.11511924e-04 7.16564532e-02 1.47091987e-02]
 [4.09890738e-03 1.30155746e-01 1.90334781e-03 1.21945028e-02]
 [1.19488167e-03 1.69592630e-03 7.62155701e-01 4.95255659e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.34176213e-01 3.78481267e-02 9.13332005e-01 4.46498931e-02]
 [1.57961668e-01 9.99830486e-01 1.55186356e-01 1.48739204e-01]
 [0.00000000e+00 0.00000000e+0

In [44]:
print ("Score over time: " +  str(sum(rewards)/total_episodes))
print(qtable)

Score over time: 0.498695
[[1.35891314e-01 1.50147115e-02 9.66188671e-03 1.32516118e-02]
 [6.65993866e-03 6.30789700e-03 2.77848685e-03 2.33906095e-01]
 [1.44666997e-03 5.31771136e-03 2.45483791e-03 3.13501173e-01]
 [1.58677143e-03 1.50669971e-03 2.06820647e-03 6.29330480e-03]
 [1.31522945e-01 3.78169439e-03 1.85057215e-02 4.14862219e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.47631392e-06 8.03449350e-06 3.36972909e-02 4.28983758e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [5.60846601e-03 5.87644438e-05 2.99585558e-03 9.94870442e-02]
 [1.87811839e-03 3.89868040e-01 4.16956352e-02 8.88217503e-03]
 [1.66004145e-01 2.84356048e-04 4.71589310e-04 5.13510144e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.20245616e-02 1.77151930e-01 2.04491122e-01 2.25131291e-02]
 [2.60641217e-01 5.16408390e-01 1.23006939e-01 2.68794862e-01]
 [0.00000000e+00 0.00000000e+

In [45]:
env.reset()

for episode in range(5):
    state = env.reset()
    step = 0
    done = False
    
    for step in range(max_steps):
        action = np.argmax(qtable[state,:])
        new_state, reward, done, info = env.step(action)
        #print(new_state, reward, done, info)
        if done:
            env.render()
            print("Number of steps", step)
            break
        state = new_state
env.close()
            

  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 34
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 46
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 46
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 49
  (Right)
SFFF
FHFH
FFFH
HFFG
Number of steps 86
